'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.235
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="workplace")>  _
Partial Public Class DataClassesDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Definitionen der Erweiterungsmethoden"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertProjects(instance As Projects)
    End Sub
  Partial Private Sub UpdateProjects(instance As Projects)
    End Sub
  Partial Private Sub DeleteProjects(instance As Projects)
    End Sub
  Partial Private Sub InsertLicences(instance As Licences)
    End Sub
  Partial Private Sub UpdateLicences(instance As Licences)
    End Sub
  Partial Private Sub DeleteLicences(instance As Licences)
    End Sub
  Partial Private Sub InsertProfiles(instance As Profiles)
    End Sub
  Partial Private Sub UpdateProfiles(instance As Profiles)
    End Sub
  Partial Private Sub DeleteProfiles(instance As Profiles)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("workplaceConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property Projects() As System.Data.Linq.Table(Of Projects)
		Get
			Return Me.GetTable(Of Projects)
		End Get
	End Property
	
	Public ReadOnly Property Licences() As System.Data.Linq.Table(Of Licences)
		Get
			Return Me.GetTable(Of Licences)
		End Get
	End Property
	
	Public ReadOnly Property Profiles() As System.Data.Linq.Table(Of Profiles)
		Get
			Return Me.GetTable(Of Profiles)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Projects")>  _
Partial Public Class Projects
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _projectID As System.Guid
	
	Private _Name As String
	
	Private _Street As String
	
	Private _Zip As String
	
	Private _Town As String
	
	Private _ContactID As System.Nullable(Of System.Guid)
	
	Private _Phone As String
	
	Private _Fax As String
	
	Private _licenceID As System.Nullable(Of System.Guid)
	
	Private _isActive As System.Nullable(Of Boolean)
	
    #Region "Definitionen der Erweiterungsmethoden"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnprojectIDChanging(value As System.Guid)
    End Sub
    Partial Private Sub OnprojectIDChanged()
    End Sub
    Partial Private Sub OnNameChanging(value As String)
    End Sub
    Partial Private Sub OnNameChanged()
    End Sub
    Partial Private Sub OnStreetChanging(value As String)
    End Sub
    Partial Private Sub OnStreetChanged()
    End Sub
    Partial Private Sub OnZipChanging(value As String)
    End Sub
    Partial Private Sub OnZipChanged()
    End Sub
    Partial Private Sub OnTownChanging(value As String)
    End Sub
    Partial Private Sub OnTownChanged()
    End Sub
    Partial Private Sub OnContactIDChanging(value As System.Nullable(Of System.Guid))
    End Sub
    Partial Private Sub OnContactIDChanged()
    End Sub
    Partial Private Sub OnPhoneChanging(value As String)
    End Sub
    Partial Private Sub OnPhoneChanged()
    End Sub
    Partial Private Sub OnFaxChanging(value As String)
    End Sub
    Partial Private Sub OnFaxChanged()
    End Sub
    Partial Private Sub OnlicenceIDChanging(value As System.Nullable(Of System.Guid))
    End Sub
    Partial Private Sub OnlicenceIDChanged()
    End Sub
    Partial Private Sub OnisActiveChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnisActiveChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_projectID", DbType:="UniqueIdentifier NOT NULL", IsPrimaryKey:=true)>  _
	Public Property projectID() As System.Guid
		Get
			Return Me._projectID
		End Get
		Set
			If ((Me._projectID = value)  _
						= false) Then
				Me.OnprojectIDChanging(value)
				Me.SendPropertyChanging
				Me._projectID = value
				Me.SendPropertyChanged("projectID")
				Me.OnprojectIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Name", DbType:="NVarChar(250) NOT NULL", CanBeNull:=false)>  _
	Public Property Name() As String
		Get
			Return Me._Name
		End Get
		Set
			If (String.Equals(Me._Name, value) = false) Then
				Me.OnNameChanging(value)
				Me.SendPropertyChanging
				Me._Name = value
				Me.SendPropertyChanged("Name")
				Me.OnNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Street", DbType:="NVarChar(250)")>  _
	Public Property Street() As String
		Get
			Return Me._Street
		End Get
		Set
			If (String.Equals(Me._Street, value) = false) Then
				Me.OnStreetChanging(value)
				Me.SendPropertyChanging
				Me._Street = value
				Me.SendPropertyChanged("Street")
				Me.OnStreetChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Zip", DbType:="NVarChar(50)")>  _
	Public Property Zip() As String
		Get
			Return Me._Zip
		End Get
		Set
			If (String.Equals(Me._Zip, value) = false) Then
				Me.OnZipChanging(value)
				Me.SendPropertyChanging
				Me._Zip = value
				Me.SendPropertyChanged("Zip")
				Me.OnZipChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Town", DbType:="NVarChar(150)")>  _
	Public Property Town() As String
		Get
			Return Me._Town
		End Get
		Set
			If (String.Equals(Me._Town, value) = false) Then
				Me.OnTownChanging(value)
				Me.SendPropertyChanging
				Me._Town = value
				Me.SendPropertyChanged("Town")
				Me.OnTownChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ContactID", DbType:="UniqueIdentifier")>  _
	Public Property ContactID() As System.Nullable(Of System.Guid)
		Get
			Return Me._ContactID
		End Get
		Set
			If (Me._ContactID.Equals(value) = false) Then
				Me.OnContactIDChanging(value)
				Me.SendPropertyChanging
				Me._ContactID = value
				Me.SendPropertyChanged("ContactID")
				Me.OnContactIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Phone", DbType:="NVarChar(50)")>  _
	Public Property Phone() As String
		Get
			Return Me._Phone
		End Get
		Set
			If (String.Equals(Me._Phone, value) = false) Then
				Me.OnPhoneChanging(value)
				Me.SendPropertyChanging
				Me._Phone = value
				Me.SendPropertyChanged("Phone")
				Me.OnPhoneChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Fax", DbType:="NVarChar(50)")>  _
	Public Property Fax() As String
		Get
			Return Me._Fax
		End Get
		Set
			If (String.Equals(Me._Fax, value) = false) Then
				Me.OnFaxChanging(value)
				Me.SendPropertyChanging
				Me._Fax = value
				Me.SendPropertyChanged("Fax")
				Me.OnFaxChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_licenceID", DbType:="UniqueIdentifier")>  _
	Public Property licenceID() As System.Nullable(Of System.Guid)
		Get
			Return Me._licenceID
		End Get
		Set
			If (Me._licenceID.Equals(value) = false) Then
				Me.OnlicenceIDChanging(value)
				Me.SendPropertyChanging
				Me._licenceID = value
				Me.SendPropertyChanged("licenceID")
				Me.OnlicenceIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_isActive", DbType:="Bit")>  _
	Public Property isActive() As System.Nullable(Of Boolean)
		Get
			Return Me._isActive
		End Get
		Set
			If (Me._isActive.Equals(value) = false) Then
				Me.OnisActiveChanging(value)
				Me.SendPropertyChanging
				Me._isActive = value
				Me.SendPropertyChanged("isActive")
				Me.OnisActiveChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Licences")>  _
Partial Public Class Licences
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _licenceID As System.Guid
	
	Private _Name As String
	
	Private _MaxTeams As System.Nullable(Of Integer)
	
	Private _MaxUsers As System.Nullable(Of Integer)
	
	Private _NettoPrice As System.Nullable(Of Decimal)
	
    #Region "Definitionen der Erweiterungsmethoden"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnlicenceIDChanging(value As System.Guid)
    End Sub
    Partial Private Sub OnlicenceIDChanged()
    End Sub
    Partial Private Sub OnNameChanging(value As String)
    End Sub
    Partial Private Sub OnNameChanged()
    End Sub
    Partial Private Sub OnMaxTeamsChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnMaxTeamsChanged()
    End Sub
    Partial Private Sub OnMaxUsersChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnMaxUsersChanged()
    End Sub
    Partial Private Sub OnNettoPriceChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnNettoPriceChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_licenceID", DbType:="UniqueIdentifier NOT NULL", IsPrimaryKey:=true)>  _
	Public Property licenceID() As System.Guid
		Get
			Return Me._licenceID
		End Get
		Set
			If ((Me._licenceID = value)  _
						= false) Then
				Me.OnlicenceIDChanging(value)
				Me.SendPropertyChanging
				Me._licenceID = value
				Me.SendPropertyChanged("licenceID")
				Me.OnlicenceIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Name", DbType:="NVarChar(50)")>  _
	Public Property Name() As String
		Get
			Return Me._Name
		End Get
		Set
			If (String.Equals(Me._Name, value) = false) Then
				Me.OnNameChanging(value)
				Me.SendPropertyChanging
				Me._Name = value
				Me.SendPropertyChanged("Name")
				Me.OnNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MaxTeams", DbType:="Int")>  _
	Public Property MaxTeams() As System.Nullable(Of Integer)
		Get
			Return Me._MaxTeams
		End Get
		Set
			If (Me._MaxTeams.Equals(value) = false) Then
				Me.OnMaxTeamsChanging(value)
				Me.SendPropertyChanging
				Me._MaxTeams = value
				Me.SendPropertyChanged("MaxTeams")
				Me.OnMaxTeamsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MaxUsers", DbType:="Int")>  _
	Public Property MaxUsers() As System.Nullable(Of Integer)
		Get
			Return Me._MaxUsers
		End Get
		Set
			If (Me._MaxUsers.Equals(value) = false) Then
				Me.OnMaxUsersChanging(value)
				Me.SendPropertyChanging
				Me._MaxUsers = value
				Me.SendPropertyChanged("MaxUsers")
				Me.OnMaxUsersChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NettoPrice", DbType:="Decimal(18,2)")>  _
	Public Property NettoPrice() As System.Nullable(Of Decimal)
		Get
			Return Me._NettoPrice
		End Get
		Set
			If (Me._NettoPrice.Equals(value) = false) Then
				Me.OnNettoPriceChanging(value)
				Me.SendPropertyChanging
				Me._NettoPrice = value
				Me.SendPropertyChanged("NettoPrice")
				Me.OnNettoPriceChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Profiles")>  _
Partial Public Class Profiles
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _userID As System.Guid
	
	Private _FirstName As String
	
	Private _LastName As String
	
	Private _Birthdate As System.Nullable(Of Date)
	
	Private _Street As String
	
	Private _Town As String
	
	Private _Zip As String
	
	Private _Qualification As String
	
	Private _WeeklyHours As System.Nullable(Of Decimal)
	
	Private _Holidays As System.Nullable(Of Decimal)
	
	Private _TaxClass As String
	
	Private _Salary As System.Nullable(Of Decimal)
	
	Private _Image As String
	
	Private _Phone As String
	
	Private _Mobile As String
	
	Private _Notes As String
	
	Private _StartDate As System.Nullable(Of Date)
	
	Private _EndDate As System.Nullable(Of Date)
	
    #Region "Definitionen der Erweiterungsmethoden"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnuserIDChanging(value As System.Guid)
    End Sub
    Partial Private Sub OnuserIDChanged()
    End Sub
    Partial Private Sub OnFirstNameChanging(value As String)
    End Sub
    Partial Private Sub OnFirstNameChanged()
    End Sub
    Partial Private Sub OnLastNameChanging(value As String)
    End Sub
    Partial Private Sub OnLastNameChanged()
    End Sub
    Partial Private Sub OnBirthdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnBirthdateChanged()
    End Sub
    Partial Private Sub OnStreetChanging(value As String)
    End Sub
    Partial Private Sub OnStreetChanged()
    End Sub
    Partial Private Sub OnTownChanging(value As String)
    End Sub
    Partial Private Sub OnTownChanged()
    End Sub
    Partial Private Sub OnZipChanging(value As String)
    End Sub
    Partial Private Sub OnZipChanged()
    End Sub
    Partial Private Sub OnQualificationChanging(value As String)
    End Sub
    Partial Private Sub OnQualificationChanged()
    End Sub
    Partial Private Sub OnWeeklyHoursChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnWeeklyHoursChanged()
    End Sub
    Partial Private Sub OnHolidaysChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnHolidaysChanged()
    End Sub
    Partial Private Sub OnTaxClassChanging(value As String)
    End Sub
    Partial Private Sub OnTaxClassChanged()
    End Sub
    Partial Private Sub OnSalaryChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnSalaryChanged()
    End Sub
    Partial Private Sub OnImageChanging(value As String)
    End Sub
    Partial Private Sub OnImageChanged()
    End Sub
    Partial Private Sub OnPhoneChanging(value As String)
    End Sub
    Partial Private Sub OnPhoneChanged()
    End Sub
    Partial Private Sub OnMobileChanging(value As String)
    End Sub
    Partial Private Sub OnMobileChanged()
    End Sub
    Partial Private Sub OnNotesChanging(value As String)
    End Sub
    Partial Private Sub OnNotesChanged()
    End Sub
    Partial Private Sub OnStartDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnStartDateChanged()
    End Sub
    Partial Private Sub OnEndDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnEndDateChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_userID", DbType:="UniqueIdentifier NOT NULL", IsPrimaryKey:=true)>  _
	Public Property userID() As System.Guid
		Get
			Return Me._userID
		End Get
		Set
			If ((Me._userID = value)  _
						= false) Then
				Me.OnuserIDChanging(value)
				Me.SendPropertyChanging
				Me._userID = value
				Me.SendPropertyChanged("userID")
				Me.OnuserIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FirstName", DbType:="NVarChar(50)")>  _
	Public Property FirstName() As String
		Get
			Return Me._FirstName
		End Get
		Set
			If (String.Equals(Me._FirstName, value) = false) Then
				Me.OnFirstNameChanging(value)
				Me.SendPropertyChanging
				Me._FirstName = value
				Me.SendPropertyChanged("FirstName")
				Me.OnFirstNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LastName", DbType:="NVarChar(50)")>  _
	Public Property LastName() As String
		Get
			Return Me._LastName
		End Get
		Set
			If (String.Equals(Me._LastName, value) = false) Then
				Me.OnLastNameChanging(value)
				Me.SendPropertyChanging
				Me._LastName = value
				Me.SendPropertyChanged("LastName")
				Me.OnLastNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Birthdate", DbType:="Date")>  _
	Public Property Birthdate() As System.Nullable(Of Date)
		Get
			Return Me._Birthdate
		End Get
		Set
			If (Me._Birthdate.Equals(value) = false) Then
				Me.OnBirthdateChanging(value)
				Me.SendPropertyChanging
				Me._Birthdate = value
				Me.SendPropertyChanged("Birthdate")
				Me.OnBirthdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Street", DbType:="NVarChar(250)")>  _
	Public Property Street() As String
		Get
			Return Me._Street
		End Get
		Set
			If (String.Equals(Me._Street, value) = false) Then
				Me.OnStreetChanging(value)
				Me.SendPropertyChanging
				Me._Street = value
				Me.SendPropertyChanged("Street")
				Me.OnStreetChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Town", DbType:="NVarChar(150)")>  _
	Public Property Town() As String
		Get
			Return Me._Town
		End Get
		Set
			If (String.Equals(Me._Town, value) = false) Then
				Me.OnTownChanging(value)
				Me.SendPropertyChanging
				Me._Town = value
				Me.SendPropertyChanged("Town")
				Me.OnTownChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Zip", DbType:="NVarChar(50)")>  _
	Public Property Zip() As String
		Get
			Return Me._Zip
		End Get
		Set
			If (String.Equals(Me._Zip, value) = false) Then
				Me.OnZipChanging(value)
				Me.SendPropertyChanging
				Me._Zip = value
				Me.SendPropertyChanged("Zip")
				Me.OnZipChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Qualification", DbType:="Text", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property Qualification() As String
		Get
			Return Me._Qualification
		End Get
		Set
			If (String.Equals(Me._Qualification, value) = false) Then
				Me.OnQualificationChanging(value)
				Me.SendPropertyChanging
				Me._Qualification = value
				Me.SendPropertyChanged("Qualification")
				Me.OnQualificationChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WeeklyHours", DbType:="Decimal(18,2)")>  _
	Public Property WeeklyHours() As System.Nullable(Of Decimal)
		Get
			Return Me._WeeklyHours
		End Get
		Set
			If (Me._WeeklyHours.Equals(value) = false) Then
				Me.OnWeeklyHoursChanging(value)
				Me.SendPropertyChanging
				Me._WeeklyHours = value
				Me.SendPropertyChanged("WeeklyHours")
				Me.OnWeeklyHoursChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Holidays", DbType:="Decimal(18,2)")>  _
	Public Property Holidays() As System.Nullable(Of Decimal)
		Get
			Return Me._Holidays
		End Get
		Set
			If (Me._Holidays.Equals(value) = false) Then
				Me.OnHolidaysChanging(value)
				Me.SendPropertyChanging
				Me._Holidays = value
				Me.SendPropertyChanged("Holidays")
				Me.OnHolidaysChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TaxClass", DbType:="NVarChar(50)")>  _
	Public Property TaxClass() As String
		Get
			Return Me._TaxClass
		End Get
		Set
			If (String.Equals(Me._TaxClass, value) = false) Then
				Me.OnTaxClassChanging(value)
				Me.SendPropertyChanging
				Me._TaxClass = value
				Me.SendPropertyChanged("TaxClass")
				Me.OnTaxClassChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Salary", DbType:="Decimal(18,2)")>  _
	Public Property Salary() As System.Nullable(Of Decimal)
		Get
			Return Me._Salary
		End Get
		Set
			If (Me._Salary.Equals(value) = false) Then
				Me.OnSalaryChanging(value)
				Me.SendPropertyChanging
				Me._Salary = value
				Me.SendPropertyChanged("Salary")
				Me.OnSalaryChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Image", DbType:="NVarChar(50)")>  _
	Public Property Image() As String
		Get
			Return Me._Image
		End Get
		Set
			If (String.Equals(Me._Image, value) = false) Then
				Me.OnImageChanging(value)
				Me.SendPropertyChanging
				Me._Image = value
				Me.SendPropertyChanged("Image")
				Me.OnImageChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Phone", DbType:="NVarChar(50)")>  _
	Public Property Phone() As String
		Get
			Return Me._Phone
		End Get
		Set
			If (String.Equals(Me._Phone, value) = false) Then
				Me.OnPhoneChanging(value)
				Me.SendPropertyChanging
				Me._Phone = value
				Me.SendPropertyChanged("Phone")
				Me.OnPhoneChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Mobile", DbType:="NVarChar(50)")>  _
	Public Property Mobile() As String
		Get
			Return Me._Mobile
		End Get
		Set
			If (String.Equals(Me._Mobile, value) = false) Then
				Me.OnMobileChanging(value)
				Me.SendPropertyChanging
				Me._Mobile = value
				Me.SendPropertyChanged("Mobile")
				Me.OnMobileChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Notes", DbType:="Text", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property Notes() As String
		Get
			Return Me._Notes
		End Get
		Set
			If (String.Equals(Me._Notes, value) = false) Then
				Me.OnNotesChanging(value)
				Me.SendPropertyChanging
				Me._Notes = value
				Me.SendPropertyChanged("Notes")
				Me.OnNotesChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_StartDate", DbType:="Date")>  _
	Public Property StartDate() As System.Nullable(Of Date)
		Get
			Return Me._StartDate
		End Get
		Set
			If (Me._StartDate.Equals(value) = false) Then
				Me.OnStartDateChanging(value)
				Me.SendPropertyChanging
				Me._StartDate = value
				Me.SendPropertyChanged("StartDate")
				Me.OnStartDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EndDate", DbType:="Date")>  _
	Public Property EndDate() As System.Nullable(Of Date)
		Get
			Return Me._EndDate
		End Get
		Set
			If (Me._EndDate.Equals(value) = false) Then
				Me.OnEndDateChanging(value)
				Me.SendPropertyChanging
				Me._EndDate = value
				Me.SendPropertyChanged("EndDate")
				Me.OnEndDateChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
